{
    var f = meta.compile("34 + 35")
    io.println(f)
    io.println(f())
}

{
    var f = meta.compile("Oops@")
    io.println("Row:", f.row())
    io.println("Col:", f.col())
    io.println("Line:", f.line())
    io.println("Message:", f.message())
    io.println("Explanation:", f.explanation())
    io.println("Example:", f.example())
}

io.println(meta.eval("500 - 80"))

io.println(meta.eval({{
    for i in 0..10 {
        io.println('Nice!')
    }
}}))

io.println(meta.eval("Hehe@"))
