{
    var xs = {
        foo = 69,
        bar = 420
    }

    var ys = xs.copy()
    var zs = xs

    io.println("xs = {xs}")
    io.println("ys = {ys}")
    io.println("zs = {zs}")

    xs.bar = 1337

    io.println("xs = {xs}")
    io.println("ys = {ys}")
    io.println("zs = {zs}")
}

{
    var xs = {
        foo = 69,
        bar = 420
    }

    var ys = {
        foo = 69,
        bar = 420
    }

    io.println(xs == xs)
    io.println(xs == ys)

    xs.bar = 1337

    io.println(xs == ys)
}

{
    var xs = {
        foo = 69,
        bar = 420
    }

    var ys = {
        bar = 1337,
        baz = 42
    }

    var zs = {
        bar = 420,
        lol = 420
    }

    io.println(xs)

    xs.extend(ys, true)
    io.println(xs)

    xs.extend(zs, false)
    io.println(xs)
}
