var x

# Basic
x = 34
x += 35
io.println(x)

x = 500
x -= 80
io.println(x)

x = 23
x *= 3
io.println(x)

x = 840
x /= 2
io.println(x)

x = 100
x %= 3
io.println(x)

x = -100
x %= 3
io.println(x)

x = -100.4
x %= 3
io.println(x)

x = -100.4
x %= 3.6
io.println(x)

# Decimals
x = 17.25
x *= 4
io.println(x)

x = 840
x *= 0.5
io.println(x)

# Bitwise
x = 276
x >>= 2
io.println(x)

x = 105
x <<= 2
io.println(x)

x = 77
x &= 103
io.println(x)

x = 160
x |= 260
io.println(x)

x = 69
x ^= 1404
io.println(x)
