name: CI

on: [push, pull_request]

jobs:
  build-test-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc
          ./build/pcre.sh

      - name: Build the project
        run: ./build/linux.sh

      - name: Run Tests
        run: |
          cd tests && ./rere.py replay test.list

  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64
          ./build/pcre.sh win32

      - name: Cross-Compile for Windows
        run: ./build/windows.sh

      - name: Archive Windows build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            bin
            lib

  test-windows:
    runs-on: windows-latest
    needs: build-windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Windows build artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-artifacts

      - name: Run Tests
        run: |
          cd tests && python3 rere.py replay test.list

  build-test-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: ./build/pcre.sh

      - name: Build the project
        run: ./build/macos.sh

      - name: Run Tests
        run: |
          cd tests && ./rere.py replay test.list
