name: CI

on: [push, pull_request]

jobs:
  build-test-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc
          ./build/pcre.sh

      - name: Build the project
        run: ./build/linux.sh

      - name: Run Tests
        run: |
          cd tests
          cc -I../include -o ffi/addsub.so -fPIC -shared ffi/addsub.c ../lib/libbs.so
          cc -I../include -o ffi/invalid.so -fPIC -shared ffi/invalid.c ../lib/libbs.so
          ./rere.py replay test.list

  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64
          ./build/pcre.sh win32

      - name: Cross-Compile for Windows
        run: ./build/windows.sh

      - name: Archive Windows build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            bin
            lib

  test-windows:
    runs-on: windows-latest
    needs: build-windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Windows build artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-artifacts

      - name: Setup MinGW
        run: |
          choco install mingw -y

      - name: Run Tests
        run: |
          cd tests
          cc -I../include -o ffi/addsub.dll -fPIC -shared ffi/addsub.c ../lib/libbs.lib
          cc -I../include -o ffi/invalid.dll -fPIC -shared ffi/invalid.c ../lib/libbs.lib
          python3 rere.py replay test.list

  build-test-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: ./build/pcre.sh

      - name: Build the project
        run: ./build/macos.sh

      - name: Run Tests
        run: |
          export DYLD_LIBRARY_PATH=$PWD/lib:$DYLD_LIBRARY_PATH
          cd tests
          cc -I../include -o ffi/addsub.dylib -fPIC -shared ffi/addsub.c ../lib/libbs.dylib
          cc -I../include -o ffi/invalid.dylib -fPIC -shared ffi/invalid.c ../lib/libbs.dylib
          ./rere.py replay test.list
