name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86_64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Linux build
        if: matrix.os == 'ubuntu-latest'
        run: ./build/linux.sh

      - name: macOS build
        if: matrix.os == 'macos-latest'
        run: ./build/macos.sh

      - name: Windows build
        if: matrix.os == 'windows-latest'
        run: |
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          build\windows.bat
        shell: cmd

      - name: Linux tests
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd tests
          cc -o executables/echo_args executables/echo_args.c
          cc -o executables/echo_stdin executables/echo_stdin.c
          cc -I../include -o executables/addsub.so -fPIC -shared executables/addsub.c ../lib/libbs.so
          cc -I../include -o executables/invalid.so -fPIC -shared executables/invalid.c ../lib/libbs.so
          ./rere.py replay test.list

      - name: macOS tests
        if: matrix.os == 'macos-latest'
        run: |
          export DYLD_LIBRARY_PATH=$PWD/lib:$DYLD_LIBRARY_PATH
          cd tests
          cc -o executables/echo_args executables/echo_args.c
          cc -o executables/echo_stdin executables/echo_stdin.c
          cc -I../include -o executables/addsub.dylib -fPIC -shared executables/addsub.c ../lib/libbs.dylib
          cc -I../include -o executables/invalid.dylib -fPIC -shared executables/invalid.c ../lib/libbs.dylib
          ./rere.py replay test.list

      - name: Windows tests
        if: matrix.os == 'windows-latest'
        run: |
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          cd tests
          cl /Fe:executables\echo_args.exe executables\echo_args.c
          cl /Fe:executables\echo_stdin.exe executables\echo_stdin.c
          cl /I..\include /LD /Foexecutables\ /Fe:executables\addsub.dll executables\addsub.c ..\lib\libbs.lib
          cl /I..\include /LD /Foexecutables\ /Fe:executables\invalid.dll executables\invalid.c ..\lib\libbs.lib
          python3 rere.py replay test.list
        shell: cmd

      - name: POSIX archive
        if: startsWith(github.ref, 'refs/tags/') && matrix.os != 'windows-latest'
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            rm -r lib/.build

            name="bs-linux-${{ matrix.arch }}"
            mkdir $name
            mv bin lib $name

            zip -r $name.zip $name
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            rm -r lib/.build

            name="bs-macos-${{ matrix.arch }}"
            mkdir $name
            mv bin lib $name

            zip -r $name.zip $name
          fi

      - name: Windows archive
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'windows-latest'
        run: |
          rm -r lib/.build

          $name="bs-windows-${{ matrix.arch }}"
          mkdir $name
          Move-Item bin, lib -Destination $name

          Compress-Archive -Path $name -DestinationPath "$name.zip"

      - name: Upload build artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-build
          path: |
            bs-linux-${{ matrix.arch }}.zip
            bs-macos-${{ matrix.arch }}.zip
            bs-windows-${{ matrix.arch }}.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ubuntu-latest-x86_64-build/bs-linux-x86_64.zip
            macos-latest-x86_64-build/bs-macos-x86_64.zip
            windows-latest-x86_64-build/bs-windows-x86_64.zip
