name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [linux, windows, macos]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          if [ "${{ matrix.target }}" == "windows" ]; then
            sudo apt-get install -y mingw-w64
            ./build/pcre.sh win32
          else
            ./build/pcre.sh
          fi

      - name: Build the project
        run: |
          if [ "${{ matrix.target }}" == "linux" ]; then
            ./build/linux.sh
          elif [ "${{ matrix.target }}" == "macos" ]; then
            ./build/macos.sh
          elif [ "${{ matrix.target }}" == "windows" ]; then
            ./build/windows.sh
          fi

      - name: Run tests
        run: |
          cd tests
          ./rere.py replay test.list
