name: CI

on: [push, pull_request]

jobs:
  build-test-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build the project
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build . --config Release

      - name: Run Tests
        run: |
          cd tests
          cc -I../include -o ffi/addsub.so -fPIC -shared ffi/addsub.c ../lib/libbs.so
          cc -I../include -o ffi/invalid.so -fPIC -shared ffi/invalid.c ../lib/libbs.so
          ./rere.py replay test.list

  build-test-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build the project
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build . --config Release

      - name: Run Tests
        shell: cmd
        run: |
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          cd tests
          cl /I"..\include" /LD /Fe:ffi\addsub.dll ffi\addsub.c ..\lib\libbs.lib
          cl /I"..\include" /LD /Fe:ffi\invalid.dll ffi\invalid.c ..\lib\libbs.lib
          python3 rere.py replay test.list

  build-test-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build the project
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build . --config Release

      - name: Run Tests
        run: |
          export DYLD_LIBRARY_PATH=$PWD/lib:$DYLD_LIBRARY_PATH
          cd tests
          cc -I../include -o ffi/addsub.dylib -fPIC -shared ffi/addsub.c ../lib/libbs.dylib
          cc -I../include -o ffi/invalid.dylib -fPIC -shared ffi/invalid.c ../lib/libbs.dylib
          ./rere.py replay test.list
